changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
    - title: Maintenance
      labels:
        - documentation
        - chore
        - maintenance

